import { EstimationResponse, SkillLevel } from './types';

export function formatEstimationComment(
  response: EstimationResponse,
  skillLevels: SkillLevel[]
): string {
  const header = `## 🕒 Development Time Estimation

This PR has been analyzed to estimate development time for different skill levels:

`;

  const estimationsSection = skillLevels
    .map(level => {
      const estimation = response.estimations[level];
      const icon = getComplexityIcon(estimation.complexity);
      
      return `### ${getSkillLevelIcon(level)} ${level} Developer
- **⏱️ Time Estimate:** ${estimation.timeEstimate}
- **🎯 Complexity:** ${icon} ${estimation.complexity}
- **💭 Reasoning:** ${estimation.reasoning}
`;
    })
    .join('\n');

  const footer = `
---
*Estimates are generated using AI and should be used as guidance only. Actual development time may vary based on specific requirements, existing codebase familiarity, and other factors.*

*Generated by [Estimate Dev Time Action](https://github.com/your-username/estimate-dev-time-action)*
`;

  return header + estimationsSection + footer;
}

function getSkillLevelIcon(level: SkillLevel): string {
  switch (level) {
    case 'Junior':
      return '🌱';
    case 'Senior':
      return '🚀';
    case 'Expert':
      return '⭐';
    default:
      return '👨‍💻';
  }
}

function getComplexityIcon(complexity: string): string {
  switch (complexity.toLowerCase()) {
    case 'low':
      return '🟢';
    case 'medium':
      return '🟡';
    case 'high':
      return '🔴';
    default:
      return '⚪';
  }
}